'use server'

import { redirect } from 'next/navigation'
import { getAuthenticatedContext, createAdminClient } from '@/lib/supabase/server'
import { sendDecisionNotification } from '@/lib/email/resend'
import type { DecisionValue, CollaborationEntryType, CollaborationEntryVisibility } from '@/types'
import { STATUS_LABELS } from '@/types'

const ALLOWED_DECISIONS: DecisionValue[] = ['interview', 'hold', 'rejected']

export type DecisionState = { error: string } | null

export async function submitDecision(
  _prevState: DecisionState,
  formData: FormData
): Promise<DecisionState> {
  const candidateId = formData.get('candidate_id')
  const decision = formData.get('decision')
  const rawNotes = formData.get('notes')

  if (typeof candidateId !== 'string' || !candidateId) {
    return { error: 'Invalid request.' }
  }
  if (typeof decision !== 'string' || !ALLOWED_DECISIONS.includes(decision as DecisionValue)) {
    return { error: 'Invalid decision value.' }
  }

  const validatedDecision = decision as DecisionValue
  // Treat notes as optional: trim whitespace, convert empty string to null.
  const notes = typeof rawNotes === 'string' ? rawNotes.trim() || null : null

  // 1 + 2. Resolve authenticated user and company_id server-side.
  const { supabase, companyId } = await getAuthenticatedContext()
  if (!companyId) return { error: 'Account configuration error.' }

  // 3. Verify candidate ownership AND fetch review_token in one query.
  //    The authenticated (RLS-scoped) client enforces that the candidate
  //    must exist AND belong to the authenticated user's company.
  //    review_token stays server-side — it is never sent to the client
  //    and never appears in FormData. It is only used in step 4 below.
  const { data: candidate, error: ownershipError } = await supabase
    .from('candidates')
    .select('id, status, full_name, recruiter_email, review_token, roles(title)')
    .eq('id', candidateId)
    .eq('company_id', companyId)
    .single()

  if (ownershipError || !candidate) {
    console.error('Decision ownership check failed:', ownershipError)
    return { error: 'Candidate not found.' }
  }

  // 4. Reject no-op: decision equals current status.
  //    Client-side disabling is a UX hint only — this is the authoritative check.
  if (candidate.status === validatedDecision) {
    return {
      error: `This candidate is already marked as ${STATUS_LABELS[validatedDecision]}.`,
    }
  }

  // 5. Apply the decision atomically via the canonical DB function.
  //    apply_candidate_review_decision updates candidates.status and inserts
  //    a decisions row inside a single transaction with a FOR UPDATE row lock,
  //    eliminating the partial-write risk of doing two separate table writes.
  //    The admin client is used here because the public review flow already
  //    uses it for this RPC call and no authenticated-client EXECUTE grant exists.
  //    Ownership was verified above — this call cannot be reached for a candidate
  //    from a different company.
  const admin = createAdminClient()
  const { data, error: rpcError } = await admin.rpc('apply_candidate_review_decision', {
    p_review_token: candidate.review_token,
    p_decision: validatedDecision,
    p_notes: notes,
  })

  if (rpcError) {
    console.error('apply_candidate_review_decision error:', rpcError)
    return { error: 'Failed to save decision. Please try again.' }
  }

  const result = data?.[0]

  if (!result) {
    console.error('apply_candidate_review_decision returned no row for candidate:', candidateId)
    return { error: 'Failed to save decision. Please try again.' }
  }

  // 5. Send recruiter notification (best-effort, non-fatal).
  if (result.recruiter_email) {
    try {
      await sendDecisionNotification({
        candidateName: result.candidate_name,
        roleTitle: result.role_title,
        decision: validatedDecision,
        notes,
        recruiterEmail: result.recruiter_email,
      })
    } catch (emailError) {
      console.error('Decision notification failed (non-fatal):', emailError)
    }
  }

  // 6. Redirect back to candidate detail with success flag.
  redirect(`/candidates/${candidateId}?decision=saved`)
}

// ─────────────────────────────────────────────────────────────────────────────
// Collaboration feed — add entry
// ─────────────────────────────────────────────────────────────────────────────

// 'handoff' is intentionally excluded — handoff entries are system-generated by
// assignOwner only. Users cannot create them via the collaboration entry form.
const ALLOWED_ENTRY_TYPES: CollaborationEntryType[] = ['note', 'interview_feedback', 'update']
const ALLOWED_VISIBILITIES: CollaborationEntryVisibility[] = ['internal', 'recruiter_visible']

export type CollaborationEntryState = { error: string } | null

export async function addCollaborationEntry(
  _prevState: CollaborationEntryState,
  formData: FormData
): Promise<CollaborationEntryState> {
  const candidateId = formData.get('candidate_id')
  const entryType = formData.get('entry_type')
  const rawBody = formData.get('body')
  const visibility = formData.get('visibility')

  // 1. Shape validation — reject obviously malformed inputs before any DB call.
  if (typeof candidateId !== 'string' || !candidateId) {
    return { error: 'Invalid request.' }
  }
  if (typeof entryType !== 'string' || !ALLOWED_ENTRY_TYPES.includes(entryType as CollaborationEntryType)) {
    return { error: 'Invalid entry type.' }
  }
  if (typeof rawBody !== 'string' || !rawBody.trim()) {
    return { error: 'Entry body is required.' }
  }
  if (rawBody.trim().length > 5000) {
    return { error: 'Entry body must be 5,000 characters or fewer.' }
  }
  if (typeof visibility !== 'string' || !ALLOWED_VISIBILITIES.includes(visibility as CollaborationEntryVisibility)) {
    return { error: 'Invalid visibility value.' }
  }

  const body = rawBody.trim()

  // 2 + 3. Resolve authenticated user and company_id server-side.
  const { supabase, user, companyId } = await getAuthenticatedContext()
  if (!companyId) return { error: 'Account configuration error.' }

  // 4. Verify the candidate belongs to this company and fetch its company_id.
  //    company_id on the new entry is derived from the candidate row — not the client.
  const { data: candidate, error: ownershipError } = await supabase
    .from('candidates')
    .select('id, company_id')
    .eq('id', candidateId)
    .eq('company_id', companyId)
    .single()

  if (ownershipError || !candidate) {
    console.error('addCollaborationEntry ownership check failed:', ownershipError)
    return { error: 'Candidate not found.' }
  }

  // 5. Insert — company_id sourced from the verified candidate row, author from the session.
  const { error: insertError } = await supabase
    .from('candidate_collaboration_entries')
    .insert({
      candidate_id: candidate.id,
      company_id: candidate.company_id,
      author_profile_id: user.id,          // profiles.id === auth.users.id
      entry_type: entryType as CollaborationEntryType,
      body,
      visibility: visibility as CollaborationEntryVisibility,
    })

  if (insertError) {
    console.error('addCollaborationEntry insert error:', insertError)
    return { error: 'Failed to save entry. Please try again.' }
  }

  redirect(`/candidates/${candidateId}?collab=entry-saved`)
}

// ─────────────────────────────────────────────────────────────────────────────
// Collaboration feed — assign / clear owner
// ─────────────────────────────────────────────────────────────────────────────

export type AssignOwnerState = { error: string } | null

export async function assignOwner(
  _prevState: AssignOwnerState,
  formData: FormData
): Promise<AssignOwnerState> {
  const candidateId = formData.get('candidate_id')
  const rawOwnerId = formData.get('owner_profile_id')

  // 1. Shape validation.
  if (typeof candidateId !== 'string' || !candidateId) {
    return { error: 'Invalid request.' }
  }

  // Empty string / absent value means "clear owner". Non-empty is passed as-is to the DB.
  // Format is not validated here — the DB lookup in step 5 is the authoritative gate:
  // an unrecognised or malformed id will simply find no matching profile row.
  const newOwnerId =
    typeof rawOwnerId === 'string' && rawOwnerId.trim() ? rawOwnerId.trim() : null

  // 2 + 3. Resolve authenticated user and company_id server-side.
  const { supabase, user, companyId } = await getAuthenticatedContext()
  if (!companyId) return { error: 'Account configuration error.' }

  // 4. Verify the candidate belongs to this company. Also fetch owner_profile_id so we
  //    can detect no-ops before writing anything.
  const { data: candidate, error: ownershipError } = await supabase
    .from('candidates')
    .select('id, company_id, full_name, owner_profile_id')
    .eq('id', candidateId)
    .eq('company_id', companyId)
    .single()

  if (ownershipError || !candidate) {
    console.error('assignOwner ownership check failed:', ownershipError)
    return { error: 'Candidate not found.' }
  }

  // 4a. No-op check — authoritative server-side guard.
  //     Client-side disabling is a UX hint only.
  if (newOwnerId === null && candidate.owner_profile_id === null) {
    return { error: 'This candidate is already unassigned.' }
  }
  if (newOwnerId !== null && newOwnerId === candidate.owner_profile_id) {
    return { error: 'This candidate is already assigned to that owner.' }
  }

  // 5. If assigning a new owner, verify the target profile belongs to the same company.
  //    This prevents a user from assigning ownership to a profile from another tenant.
  let ownerDisplayName: string | null = null
  if (newOwnerId) {
    const { data: ownerProfile, error: ownerError } = await supabase
      .from('profiles')
      .select('id, full_name, company_id')
      .eq('id', newOwnerId)
      .eq('company_id', companyId)
      .single()

    if (ownerError || !ownerProfile) {
      console.error('assignOwner target profile check failed:', ownerError)
      return { error: 'Owner profile not found.' }
    }

    ownerDisplayName = ownerProfile.full_name
  }

  // 6. Update ownership on the candidate row.
  //    Scoped by both id and company_id as a belt-and-suspenders guard.
  const { error: updateError } = await supabase
    .from('candidates')
    .update({
      owner_profile_id: newOwnerId,
      owner_updated_at: new Date().toISOString(),
    })
    .eq('id', candidate.id)
    .eq('company_id', candidate.company_id)

  if (updateError) {
    console.error('assignOwner update error:', updateError)
    return { error: 'Failed to assign owner. Please try again.' }
  }

  // 7. Auto-create a handoff collaboration entry (best-effort).
  //    The ownership update above is the authoritative state change — this entry
  //    is a convenience log. If this insert fails, ownership is still correctly
  //    recorded on candidates.owner_profile_id.
  //    Body is system-generated; the client supplies no free-form text here.
  const handoffBody = newOwnerId
    ? `Ownership assigned to ${ownerDisplayName ?? 'team member'}.`
    : 'Ownership cleared.'

  const { error: handoffError } = await supabase
    .from('candidate_collaboration_entries')
    .insert({
      candidate_id: candidate.id,
      company_id: candidate.company_id,
      author_profile_id: user.id,
      entry_type: 'handoff' as CollaborationEntryType,
      body: handoffBody,
      visibility: 'internal' as CollaborationEntryVisibility,
    })

  if (handoffError) {
    // Non-fatal — log but do not fail the request.
    console.error('assignOwner handoff entry error (non-fatal):', handoffError)
  }

  redirect(`/candidates/${candidateId}?collab=owner-updated`)
}
