'use client'

import { useActionState } from 'react'
import { addCollaborationEntry, type CollaborationEntryState } from './actions'

// handoff is intentionally excluded — it is system-generated by assignOwner only.
const USER_ENTRY_TYPES = [
  { value: 'note', label: 'Note' },
  { value: 'interview_feedback', label: 'Interview feedback' },
  { value: 'update', label: 'Update' },
] as const

const VISIBILITY_OPTIONS = [
  { value: 'internal', label: 'Internal only' },
  { value: 'recruiter_visible', label: 'Recruiter visible' },
] as const

export function CollaborationEntryForm({ candidateId }: { candidateId: string }) {
  const [state, formAction, isPending] = useActionState<CollaborationEntryState, FormData>(
    addCollaborationEntry,
    null
  )

  return (
    <form action={formAction} className="space-y-3">
      <input type="hidden" name="candidate_id" value={candidateId} />
      <textarea
        name="body"
        placeholder="Add a note, feedback, or update…"
        rows={3}
        maxLength={5000}
        disabled={isPending}
        className="w-full rounded-lg border border-zinc-200 px-3 py-2 text-sm text-zinc-800 placeholder:text-zinc-400 focus:outline-none focus:ring-2 focus:ring-zinc-900 focus:ring-offset-1 resize-none disabled:opacity-50"
      />
      <div className="flex flex-wrap items-center gap-2">
        <select
          name="entry_type"
          defaultValue="note"
          disabled={isPending}
          className="rounded-lg border border-zinc-200 px-3 py-2 text-sm text-zinc-800 focus:outline-none focus:ring-2 focus:ring-zinc-900 focus:ring-offset-1 disabled:opacity-50"
        >
          {USER_ENTRY_TYPES.map((t) => (
            <option key={t.value} value={t.value}>
              {t.label}
            </option>
          ))}
        </select>
        <select
          name="visibility"
          defaultValue="internal"
          disabled={isPending}
          className="rounded-lg border border-zinc-200 px-3 py-2 text-sm text-zinc-800 focus:outline-none focus:ring-2 focus:ring-zinc-900 focus:ring-offset-1 disabled:opacity-50"
        >
          {VISIBILITY_OPTIONS.map((v) => (
            <option key={v.value} value={v.value}>
              {v.label}
            </option>
          ))}
        </select>
        <button
          type="submit"
          disabled={isPending}
          className="ml-auto rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white hover:bg-zinc-700 active:bg-zinc-800 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isPending ? 'Saving…' : 'Add entry'}
        </button>
      </div>
      {state?.error && (
        <p className="text-sm text-red-600">{state.error}</p>
      )}
    </form>
  )
}
